//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirAPICarlos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeEstudio
    {
        public int ID { get; set; }
        public int EstudioID { get; set; }
        public int AnimeID { get; set; }
    
        public virtual Anime Anime { get; set; }
        public virtual Estudio Estudio { get; set; }
    }
}
