//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirAPICarlos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaEstreno { get; set; }
        public string Sinopsis { get; set; }
        public decimal Puntuacion { get; set; }
        public decimal Popularidad { get; set; }
        public int EstadoID { get; set; }
    }
}
