//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirAPICarlos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmimirEntities1 : DbContext
    {
        public AmimirEntities1()
            : base("name=AmimirEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anime> Anime { get; set; }
        public virtual DbSet<Paquete> Paquete { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<AnimeEstudio> AnimeEstudio { get; set; }
        public virtual DbSet<AnimeGenero> AnimeGenero { get; set; }
        public virtual DbSet<Capitulo> Capitulo { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Estudio> Estudio { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<NombreAlternativo> NombreAlternativo { get; set; }
        public virtual DbSet<Personajes> Personajes { get; set; }
        public virtual DbSet<UrlAlternativo> UrlAlternativo { get; set; }
        public virtual DbSet<RefreshTokenCLS> RefreshToken { get; set; }
    }
}
