//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirAPICarlos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshTokenCLS
    {
        public string RefreshToken { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public string ClientID { get; set; }
        public string ClientSecret { get; set; }
    }
}
