//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirAPICarlos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlAlternativo
    {
        public int ID { get; set; }
        public int CapituloID { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
    
        public virtual Capitulo Capitulo { get; set; }
    }
}
